### ISSUE TITLE
[Question] How to use with wikimedia xml data dump

### ISSUE THREAD

**Issue by ngortheone** [openzim/mediawiki-docker#29]
Pardon a possiby stupid question.

I have Wikipedia xml data dump [downloaded from here](https://meta.wikimedia.org/wiki/Data_dump_torrents#English_Wikipedia).

Is there a way to use it with this solution?
Are there any conversion steps necessary? 
If no - how can I get the most recent wikipedia data for this solution?

**Comment by pronoiac** [comment]
I'm new here, and it seems like a good question! After struggling with it for a couple of days, I don't think this is particularly well-suited for importing a large wiki dump. I don't have a better solution yet.

**Comment by kelson42** [comment]
This project is about getting an easy to setup Mediawiki instance. Your question is about handling export format XML dump from Wikipedia. This is not really the right place to talk about that.

There should be no problem to import/export these dumps within a Mediawiki setup like this project proposes... You can perfectly manipulate the MySQL database data within the Docker instance... Have a look to this kind of approach for example https://gist.github.com/spalladino/6d981f7b33f6e0afe6bb. But again, this is not the role of this project to maintain this external solution.

@pronoiac @ngortheone Having played intensively with the Wikipedia XML dumps in the past, I can tell you that (1) This is not an easy path because of the amount of data to deal with, in particular if you want to deal with Wikipedia in English (2) Most of the time, this is not the best approach to solve users problems. So, if I would have a question back, this would be: Why do you need to reimport a Wikipedia XML dump?

**Comment by ngortheone** [comment]
@kelson42 I was just trying see how hard is to spin up a personal self-hosted instance of english wikipedia.
If you know better ways - please share!

**Comment by kelson42** [comment]
@ngortheone Google will for sure tell you that Kiwix allows you to do so.

**Comment by pronoiac** [comment]
It looked like the last Kiwix archive of English Wikipedia is from 2018. I thought I'd try making a newer version.

**Comment by kelson42** [comment]
@pronoiac We are making a new one currently, you already have new version without pictures. ZIM files are made with MWoffliner, not with the dumps.
